# Configuration parameters for Monetization Monitor
data_sources:
  - type: API
    endpoint: "https://api.example.com/revenue"
    api_key: "your_api_key_here"
  - type: CSV
    file_path: "/path/to/revenue_data.csv"

model_params